language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - PACKAGE=yojson
  matrix:
  - OCAML_VERSION=4.02 OCAML_SWITCH=4.02.3
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
matrix:
  exclude:
    - os: osx
      env: OCAML_VERSION=4.02 OCAML_SWITCH=4.02.3
    - os: osx
      env: OCAML_VERSION=4.03
    - os: osx
      env: OCAML_VERSION=4.04
    - os: osx
      env: OCAML_VERSION=4.05
    - os: osx
      env: OCAML_VERSION=4.06
os:
  - linux
  - osx
